name: corona_tracker
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: 0.6.7
  flutter_svg: ^0.19.1
  freezed_annotation: ^0.7.1
  get_it: ^4.0.2
  injectable: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 0.6.7
  build_runner: null
  freezed: ^0.10.7
  injectable_generator: ^0.3.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
